### ISSUE TITLE
Error while starting mfsysmon - circus watcher for telegraf

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfsysmon#135]
In MetWork v2.2, RockyLinux 8.7, I face an error while starting mfsysmon, an ERROR is displayed while "waiting for start of telegraf" :

```
- Waiting for start of telegraf...                         [ ERROR ]
```

It appears that below command returns an error:
```
_circusctl --endpoint ipc:///home/mfsysmon/var/circus.socket status "telegraf"
error
```

While in version 2.1, it returns the expected value **active**.

See the `wait_watcher_started` method in file `circus.py` https://github.com/metwork-framework/mfext/blob/master/adm/circus.py

The call stack is:
`mfsysmon.start` ->
`_circus_wait_watcher_started.sh telegraf` ->
`layer_wrapper --layers=python3_circus@mfext -- _circus_wait_watcher_started.py telegraf` ->
`client.wait_watcher_started(name='telegraf', timeout='20')` (MetWorkCircusClient from `circus.py`)
`_circusctl --endpoint ipc:///home/mfsysmon/var/circus.socket status "telegraf"` ->
`layer_wrapper --layers=python3_circus@mfext -- python -m circus.circusctl --endpoint ipc:///home/mfsysmon/var/circus.socket status "telegraf"` ...

**Comment by matthieumarrast** [comment]
OK this is because the circus watcher for telegraf is missing in the `~/tmp/config_auto/circus.ini` file:
```
[watcher:telegraf]
cmd=log_proxy_wrapper
args=--stdout telegraf.log --stderr STDOUT -- telegraf --config /home/mfsysmon/tmp/config_auto/telegraf.conf
hooks.before_start=mfext.circus_hooks.before_start_shell
copy_env = True
autostart = True
respawn = True
numprocesses=1
stop_signal = 9
stop_children = True
max_retry=-1
```

This is because of the env variable `MFSYSMON_ADMIN_HOSTNAME=null`
Indeed we have set the below value in our `/etc/metwork.config.d/mfsysmon/config.ini` config file:
```
hostname[DEV]=null
```
If I put `hostname[DEV]=localhost` **the problem is fixed**.

**Comment by matthieumarrast** [comment]
### Conclusion:

As the config says that if the hostname is null there is no monitoring, it is not forbidden to set this value as null.

```
########################
##### ADMIN MODULE #####
########################
[admin]
# Hostname hosting the mfadmin module (if any)
# null => no monitoring
# localhost => send logs and metrics to the locally installed mfadmin module
# * => send logs and metrics to the specified host (which must host an mfadmin
#      module)
hostname=localhost
```

=> If the telegraf watcher is not started, it is useless to check its status.

So I propose to replace this in `mfsysmon.start`:
```
    _circus_wait_watcher_started.sh telegraf || RES=1
    _circus_schedule_start_watcher.sh telegraf_collector_custom_diskio telegraf_collector_custom_netstat telegraf_collector_custom_netio || RES=1
    if test "${RES}" = "0"; then
        _circus_wait_watcher_started.sh telegraf_collector_custom_diskio telegraf_collector_custom_netstat telegraf_collector_custom_netio  || RES=1
    fi

    if test "${ADMIN_HOSTNAME}" != ""; then
        if test "${ADMIN_HOSTNAME}" != "null"; then
            _circus_wait_watcher_started.sh telegraf || RES=1
            _circus_wait_watcher_started.sh telegraf_collector_metwork_module || RES=1
        fi
    fi
```
by
```
    _circus_schedule_start_watcher.sh telegraf_collector_custom_diskio telegraf_collector_custom_netstat telegraf_collector_custom_netio || RES=1
    if test "${RES}" = "0"; then
        _circus_wait_watcher_started.sh telegraf_collector_custom_diskio telegraf_collector_custom_netstat telegraf_collector_custom_netio  || RES=1
    fi

    if test "${ADMIN_HOSTNAME}" != ""; then
        if test "${ADMIN_HOSTNAME}" != "null"; then
            _circus_wait_watcher_started.sh telegraf || RES=1
            _circus_wait_watcher_started.sh telegraf_collector_metwork_module || RES=1
        fi
    fi
```
i.e remove the first call of `_circus_wait_watcher_started.sh telegraf`, where the ADMIN_HOSTNAME variable is not checked before calling it.

**Comment by thebaptiste** [comment]
It's not a big deal as `mfadmin.status` is ok, even with this error.
But ok four you fix.
